// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfobRnIZaI_1aEZO4lrbJskz3BK3wazg',
    appId: '1:888813501185:web:a6788d16c19294d923b900',
    messagingSenderId: '888813501185',
    projectId: 'hospital-management-syst-29cc7',
    authDomain: 'hospital-management-syst-29cc7.firebaseapp.com',
    storageBucket: 'hospital-management-syst-29cc7.appspot.com',
    measurementId: 'G-MWKVJQPESQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChjv_eIgZVI4FVzUAaE7AFgjroYXXiGVQ',
    appId: '1:888813501185:android:4dc58368f2e9217823b900',
    messagingSenderId: '888813501185',
    projectId: 'hospital-management-syst-29cc7',
    storageBucket: 'hospital-management-syst-29cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARdmHnYJFkl3RjxfhK5exCSQSkILNiVo4',
    appId: '1:888813501185:ios:0c5bc5fa4127101423b900',
    messagingSenderId: '888813501185',
    projectId: 'hospital-management-syst-29cc7',
    storageBucket: 'hospital-management-syst-29cc7.appspot.com',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );
}
